### ISSUE TITLE
נניח בשלילה שלא פתרת את בעיית 

### ISSUE THREAD

**Issue by YanaPatyuk** [CohenOri/AdvancedProgramming1#1]
https://github.com/CohenOri/AdvancedProgramming1/blob/6ec8b69a65cf91e2463644fe8bed66a45d7cb6b6/RegularLogic.cpp#L426

הזליגות-זו הבעיה.יש שחרור כפול של הלוח

**Comment by CohenOri** [comment]
fixed in the recent version.
